# Generated by Django 4.2.19 on 2026-05-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_categorie_id_alter_medicament_id'),
        ('pharmacies', '0004_alter_personnel_id_alter_pharmacyprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=20)),
                ('medicaments_entraines', models.JSONField(default=list)),
                ('nb_echantillons', models.IntegerField(default=0)),
                ('erreur', models.TextField(blank=True)),
                ('duree_secondes', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='pharmacies.pharmacyprofile')),
            ],
            options={
                'verbose_name': "Session d'entraînement",
                'verbose_name_plural': "Sessions d'entraînement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=50)),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField(blank=True, null=True)),
                ('n_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medicament')),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.pharmacyprofile')),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ml_module.trainingrun')),
            ],
            options={
                'verbose_name': 'Métriques de modèle',
                'verbose_name_plural': 'Métriques de modèles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LowSellerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_jours', models.IntegerField()),
                ('quantite_totale', models.IntegerField()),
                ('quantite_moyenne_journaliere', models.FloatField()),
                ('jours_depuis_derniere_vente', models.IntegerField(blank=True, null=True)),
                ('tendance', models.CharField(choices=[('BAISSE', 'En baisse'), ('STABLE', 'Stable'), ('HAUSSE', 'En hausse')], default='STABLE', max_length=10)),
                ('score_risque', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_low_seller_reports', to='catalog.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_low_seller_reports', to='pharmacies.pharmacyprofile')),
            ],
            options={
                'verbose_name': 'Rapport médicament faible vente',
                'verbose_name_plural': 'Rapports médicaments faibles ventes',
                'ordering': ['-score_risque'],
            },
        ),
        migrations.CreateModel(
            name='SalesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=50)),
                ('date_prediction', models.DateField()),
                ('quantite_predite', models.FloatField()),
                ('borne_basse', models.FloatField()),
                ('borne_haute', models.FloatField()),
                ('horizon_jours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_sales_predictions', to='catalog.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_sales_predictions', to='pharmacies.pharmacyprofile')),
            ],
            options={
                'verbose_name': 'Prédiction de ventes',
                'verbose_name_plural': 'Prédictions de ventes',
                'ordering': ['date_prediction'],
                'unique_together': {('pharmacie', 'medicament', 'modele', 'date_prediction')},
            },
        ),
    ]
