# Generated by Django 6.0.3 on 2026-03-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=200, verbose_name='Nom de la pharmacie')),
                ('numero_autorisation', models.CharField(max_length=100, unique=True, verbose_name="N° Autorisation d'exercice")),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone pharmacie')),
                ('email_pharmacie', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email pharmacie')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='pharmacies/diplomes/', verbose_name='Diplôme de pharmacien')),
                ('autorisation_exercice', models.FileField(blank=True, null=True, upload_to='pharmacies/autorisations/', verbose_name="Autorisation d'exercice")),
                ('registre_commerce', models.FileField(blank=True, null=True, upload_to='pharmacies/registres/', verbose_name='Registre de commerce')),
                ('approval_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('SUSPENDED', 'Suspendue')], default='PENDING', max_length=20, verbose_name="Statut d'approbation")),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('horaires_ouverture', models.TextField(blank=True, null=True, verbose_name="Horaires d'ouverture")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pharmacies', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien propriétaire')),
            ],
            options={
                'verbose_name': 'Profil Pharmacie',
                'verbose_name_plural': 'Profils Pharmacies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ASSISTANT', 'Assistant pharmacien'), ('VENDEUR', 'Vendeur'), ('GESTIONNAIRE', 'Gestionnaire de stock'), ('LIVREUR', 'Livreur')], default='VENDEUR', max_length=20, verbose_name='Rôle')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='pharmacies.pharmacyprofile', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'ordering': ['-created_at'],
            },
        ),
    ]
