# Generated by Django 6.0.3 on 2026-03-08 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('modele', models.CharField(default='llama3.2', help_text='Ex: llama3.2, mistral, gemma2', max_length=100, verbose_name='Modèle Ollama')),
                ('url_ollama', models.URLField(default='http://localhost:11434', verbose_name='URL Ollama API')),
                ('system_prompt', models.TextField(blank=True, help_text='Instructions pour le comportement du chatbot', null=True, verbose_name='Prompt système')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, help_text='0.0 = déterministe, 1.0 = créatif', max_digits=3, verbose_name='Température')),
                ('max_tokens', models.PositiveIntegerField(default=2048, verbose_name='Max tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Configuration Ollama',
                'verbose_name_plural': 'Configurations Ollama',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre de la conversation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant IA'), ('SYSTEM', 'Système')], max_length=20, verbose_name='Rôle')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens utilisés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_module.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prediction', models.CharField(choices=[('DEMANDE', 'Prédiction de demande'), ('RUPTURE', 'Risque de rupture'), ('TENDANCE', 'Tendance de vente')], max_length=20, verbose_name='Type de prédiction')),
                ('valeur_predite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur prédite')),
                ('unite', models.CharField(blank=True, help_text='Ex: unités, DH, %', max_length=50, null=True, verbose_name='Unité')),
                ('confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Niveau de confiance (%)')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('donnees_input', models.JSONField(blank=True, help_text='Données utilisées pour la prédiction', null=True, verbose_name="Données d'entrée")),
                ('modele_utilise', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle IA utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='catalog.medicament', verbose_name='Médicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pharmacies.pharmacyprofile', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
