# Generated by Django 6.0.3 on 2026-03-08 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône (classe CSS ou emoji)')),
                ('couleur', models.CharField(blank=True, help_text='Ex: #FF6B6B', max_length=20, null=True, verbose_name='Couleur (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('principe_actif', models.CharField(blank=True, max_length=200, null=True, verbose_name='Principe actif')),
                ('dosage', models.CharField(blank=True, help_text='Ex: 500mg, 1g', max_length=100, null=True, verbose_name='Dosage')),
                ('forme', models.CharField(blank=True, help_text='Ex: Comprimé, Sirop, Gélule', max_length=100, null=True, verbose_name='Forme')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicaments/', verbose_name='Image')),
                ('ordonnance_requise', models.BooleanField(default=False, verbose_name='Ordonnance requise')),
                ('posologie', models.TextField(blank=True, null=True, verbose_name='Posologie')),
                ('contre_indications', models.TextField(blank=True, null=True, verbose_name='Contre-indications')),
                ('effets_secondaires', models.TextField(blank=True, null=True, verbose_name='Effets secondaires')),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code-barres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='catalog.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
