# Generated by Django 6.0.3 on 2026-03-08 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Sécurité Sociale')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies connues')),
                ('antecedents_medicaux', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('medecin_traitant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médecin traitant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Patient',
                'verbose_name_plural': 'Profils Patients',
            },
        ),
    ]
